# ABOUTME: GitHub Sponsors configuration for Claudius
# ABOUTME: Enables the "Sponsor" button on the repository

github: [cesuygun]
ko_fi: cesuygun
# buy_me_a_coffee: cesuygun  # Uncomment if you set this up
# custom: ["https://your-link.com"]
